name: smart_grocery_assistant
description: "A Flutter app for managing groceries and recipes."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  google_ml_kit: ^0.20.0
  camera: ^0.10.5+9       # For camera access
  # google_ml_kit: ^0.16.4  # For OCR (text recognition)
  path_provider: ^2.1.5   # For saving the captured image
  path: ^1.8.3            # For file path utilities
  http: ^1.2.2          # For making HTTP requests
  connectivity_plus: ^6.0.5  # For checking internet connectivity
  uuid: ^4.5.0            # For generating unique IDs
  provider: ^6.1.2        # For state management
  sqflite: ^2.4.2
  speech_to_text: 6.0.0
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  assets:
    - assets/images/tomato_basil_pasta.jpg
    - assets/images/avocado_toast.jpg
    - assets/images/chicken_stir_fry.jpg

